### ISSUE TITLE
Nodes do not link up. (Solution Below)

### ISSUE THREAD

**Issue by z0z0Official** [azazeal04/ComfyUI-Styles#1]
Unable to link this style node to any sampler.

**Comment by azazeal04** [comment]
use a clip text encode node

**Comment by z0z0Official** [comment]
sadly it's not working.

**Comment by z0z0Official** [comment]
@azazeal04 CLIP TEXT Encoder (Does Not Work) 
Do you mean "Text to Conditioning" ? Because using this makes it work. You should probably specify this on your repository here on github and your upload on Civitai.com

**Comment by z0z0Official** [comment]
![Screenshot 2023-10-10 065323](https://github.com/azazeal04/ComfyUI-Styles/assets/124645295/56526cf1-0eec-4867-8ed8-ad2d426bc242)
